### ISSUE TITLE
Operation monitor

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/wordpress-pakkasmarja-management#5]
As a manager i would like to be able to monitor current and past operations

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Yhteystietojen hallinta](https://trello.com/c/eXoxrSaC/2-yhteystietojen-hallinta)

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sopimustietojen hallinta](https://trello.com/c/S82ifp7L/4-sopimustietojen-hallinta)
