### ISSUE TITLE
Contract synchronization support

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/wordpress-pakkasmarja-management#6]
As a manager i would like to be able to initialize contract synchronization from management view

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sopimustietojen hallinta](https://trello.com/c/S82ifp7L/4-sopimustietojen-hallinta)

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sopimustietojen synkronointi SAPista palvelimelle (siirtotiedosto)](https://trello.com/c/xv2x7Zcp/3-sopimustietojen-synkronointi-sapista-palvelimelle-siirtotiedosto)
